##################################################################################
#                                                             
#   DO NOT!!!! DO NOT CHANGE THE FOLLOWING CONSTANTS (unless you're a developer)
#
##################################################################################
# - min month
RAW_MIN_DATE = '2016-05'
# - max month
RAW_MAX_DATE = '2024-04'

# ALL_PRODUCTS_LABELS = [ 'sugar_price']#, 'laundry_soap_bar_price']  #testing only

ALL_PRODUCTS_LABELS = ['bread_price', 'bulgur_price', 'chicken_meat_price', 'cucumber_price',
                   'egg_price', 'kerosene_manually_refined_price','laundry_soap_bar_price', 
                   'lentil_price', 'onion_price', 'potato_price', 'rice_price', 'salt_price', 
                   'sanitary_pad_price', 'soap_price', 'sugar_price', 'tomato_paste_price', 
                   'tomato_price', 'toothpaste_price', 'vegetable_oil_price']

# Dictionary mapping product names to their respective quantities of the MEB
ALL_PRODUCT_MEB_QUANTITIES  = {
        'bulgur_price': 15,
        'rice_price': 19,
        'bread_price': 37,
        'lentil_price': 15,
        'vegetable_oil_price': 7,
        'sugar_price': 5,
        'salt_price': 1,
        'tomato_price': 4,
        'potato_price': 4,
        'onion_price': 4,
        'cucumber_price': 4,
        'chicken_meat_price': 6,
        'egg_price': 6,
        'tomato_paste_price': 6,
        'soap_price': 1.8,
        'laundry_soap_bar_price': 3,
        'toothpaste_price': 0.2,
        'sanitary_pad_price': 40,
        'kerosene_manually_refined_price': 25
    }

ADMIN_0_LABELS = []

ADMIN_1_LABELS = ['Al-Hasakeh', 'Aleppo', 'Ar-Raqqa', 'Damascus', "Dar'a", 'Deir-ez-Zor',
                'Hama', 'Homs', 'Idleb', 'Lattakia', 'Quneitra', 'Rural Damascus']

ADMIN_2_LABELS = ['', "A'zaz", 'Abu Kamal', 'Afrin', 'Ain Al Arab', 'Al Bab', 'Al Fiq',
                  "Al Ma'ra", 'Al Mayadin', 'Al-Haffa', 'Al-Hasakeh', 'Al-Malikeyyeh', 
                  'Ar-Raqqa', 'Ar-Rastan', 'Ariha', 'As-Sanamayn', 'As-Suqaylabiyah', 
                  'Ath-Thawrah', 'Damascus', "Dar'a", 'Deir-ez-Zor', 'Duma', 'Hama', 
                  'Harim', 'Homs', 'Idleb', "Izra'", 'Jarablus', 'Jebel Saman', 
                  'Jisr-Ash-Shugur', 'Lattakia', 'Menbij', 'Muhradah', 'Quamishli',
                  'Quneitra', 'Ras Al Ain', 'Rural Damascus', 'Tell Abiad']

ADMIN_3_LABELS = ['', "A'rima", "A'zaz", 'Abu Kamal', 'Abu Qalqal', 'Abul Thohur',
                   'Afrin', 'Aghtrin', 'Ain al Arab', 'Al Bab', 'Al Mayadin', 
                   'Al-Hasakeh', 'Al-Khashniyyeh', 'Al-Malikeyyeh', 'Al-Thawrah',  
                   'Amuda', "Ar-Ra'ee", 'Ar-Raqqa', 'Ar-Rastan', 'Arbin', 'Areesheh', 
                   'Ariha', 'Armanaz', 'As-Sanamayn', 'Atareb', 'Babella', 'Badama', 
                   'Basira', "Be'r Al-Hulo Al-Wardeyyeh", 'Bennsh', 'Bulbul', 
                   'Busra Esh-Sham', "Da'el", 'Damascus', 'Dana', "Dar'a", 'Darbasiyah', 
                   'Daret Azza', 'Darkosh', 'Deir-ez-Zor', 'Duma', 'Ehsem', 'Ein Issa', 
                   'Fiq', 'Ghandorah', 'Hadher', 'Hajin', 'Harim', 'Haritan', 'Heish', 
                   'Hole', 'Hrak', 'Idleb', "Izra'", 'Jandairis', 'Janudiyeh', 
                   'Jarablus', 'Jasim', 'Jawadiyah', 'Jebel Saman', 'Jisr-Ash-Shugur', 
                   'Jizeh', 'Jurneyyeh', 'Kafr Batna', 'Kafr Nobol', 'Kafr Takharim', 
                   'Kafr Zeita', 'Kansaba', 'Karama', 'Khan Arnaba', 'Khan Shaykun', 
                   'Khasham', 'Kherbet Ghazala', 'Kisreh', 'Kisweh', 'Lattakia', 
                   'Lower Shyookh', "Ma'arrat An Nu'man", "Ma'btali", 'Maadan', 
                   'Maaret Tamsrin', 'Madiq Castle', 'Mansura', "Mare'", 'Markada', 
                   'Menbij', 'Mhambal', 'Mseifra', 'Muhasan', 'Mzeireb', 'Nawa ', 
                   'Qahtaniyyeh', 'Qourqeena', 'Quamishli', 'Quneitra', 'Raju', 
                   'Ras Al Ain', 'Sabka', 'Salqin', 'Sanjar', 'Saraqab', 'Sarin', 
                   'Sarmin', 'Shadadah', 'Sharan', 'Sheikh El-Hadid', 'Suluk', 'Sur', 
                   'Suran', 'Susat', 'Tabni', 'Tal Hmis', 'Tal Tamer', 'Talbiseh', 
                   'Taldu', 'Tall Refaat', 'Tamanaah', 'Teftnaz', 'Tell Abiad', 
                   'Thiban', "Ya'robiyah", 'Zarbah', 'Ziyara']

ADMIN_4_LABELS = ['', 'Abdin (Khan Shaykun)', 'Abin - Efrin', 'Abin Samaan', 'Abtaa', 
                'Abu Hamam', 'Abu Hardoub', 'Abu Homama', 'Abu Kabret Al Rashid', 
                'Abu Kabret Tal Tamr', 'Abu Kamal', 'Abu Khashab (Kisreh)', 'Abu Qalqal',
                'Abu Rajab', 'Abu Touta', 'Abul Thohur', "Ad Dari'yeh", 'Afrin (Afrin)',
                'Afs', 'Ain Al Arab', 'Akhtrein', 'Al Areen - Kastanah Fawqan', 'Al Bab', 
                'Al Mayadin', 'Al Mufti', 'Al Thawra_ Al Jourah', 'Al-Azizieh (Ras Al Ain)', 
                'Al-Hama (Qudsiya)', 'Al-Hasakeh', "Al-Malikeyyeh (A'zaz)", 
                'Al-Malikeyyeh (Al-Malikeyyeh)', 'Al-Thawrah (Al-Thawrah)', 'Aleppo', 
                'Ali', 'Aljern Alaswad', 'Allani', 'Alshamra', 'Amin', 'Amiriya - Meirkan', 
                'Ammar Ibn Yaser', 'Amuda', 'Amudiyeh', 'Andalus', 'Andan', 'Anjara', 
                'Anqrati', 'Aqrabat (Dana)', 'Ar-Raee', 'Ar-Raqqa', 'Arab Azzah',
                'Asaliyeh (Menbij)', 'Asilah (Ar-Rastan)', 'Atareb', 'Atma',
                "Atshana (Be'r Al-Hulo Al-Wardeyyeh)", 'Azaz', 'Aziziyeh (Aghtrin)', 
                'Azmarin', 'Bab Alsalameh', 'Babella', 'Badama', 'Balyun', 
                'Basira - Basira', 'Basufan', 'Basuta', 'Batani', 'Batbu', 
                'Bayada - Jendris', 'Bazagha', 'Beeret Kaftin', 'Beit Sahm', 'Beit Sawa', 
                'Bennsh', 'Big Dara ', 'Big Hayyeh', 'Big Hir Jamus', 'Big Orm', 
                'Big Siwan', 'Bir Ajam', 'Bir Elhilu', 'Breiqa ', 'Bsames', 'Bubadran', 
                'Bulbul', 'Busra Esh-Sham', 'Bweir Bir Helo', 'City Centre', 'Dabeq',
                'Dael', 'Dana (Dana)', "Dar'a - Dar'a", 'Darbasiyah', 'Daret Azza',
                'Darkosh', 'Deir Fool', 'Deir Hassan - Darhashan', 'Deir Jmal',
                'Deir Sunbul (Madiq Castle)', 'Deir-ez-Zor', 'Dorriyeh', 'Duma (Duma)',
                'Dweidan', 'Eastern Deir', 'Eastern Ghariyeh', 'Eastern Maliha',
                'Eastern Marj Akhdar', 'Eastern Rashidiyeh', 'Eastern Tal Aar',
                'Eastern Tal Battal', 'Ehsem', 'Ehteimlat', 'Ein Al-Arus (Tell Abiad)',
                'Ein Issa', 'Ein Shib', 'Ein Terma', 'Elhisan', 'Em Al-Qura', 'Eskat',
                'Faqie (Kafr Nobol)', 'Farat', 'Fares', 'Farja (Tamanaah)', 
                'Firazdaq - Arsalan Tash', 'Forty Seven', 'Ftireh', 'Furat', 'Ghadqa',
                'Ghandorah', 'Ghasbiyeh', 'Ghasm', 'Ghassaniyeh - Qorret Halanj',
                'Ghorur', 'Hafasraja', 'Hajin', 'Halawaniyeh', 'Halbeh', 'Hamama - Kafr Debbin',
                'Hammam At-Turkman', 'Hammura', 'Hamra (Jawadiyah)', 'Hamrat Ghannam',
                'Hara (As-Sanamayn)', 'Haranbush', 'Harim', 'Haritan', 'Harjalah',
                'Has', 'Hawa', 'Hawash (Madiq Castle)', 'Hawayej', 'Hazano', 'Hazarin',
                'Hazimeh', 'Hbit', 'Hdadiyeh', 'Heish', 'Helleh (Kafr Takharim)',
                'Hettin', 'Hezreh - Hezri', 'Hijeh', 'Hilweh (Qahtaniyyeh)',
                'Hisham Ibn Abd Al Malek', 'Hisheh (Ein Issa)', 'Hole', 'Hrak',
                'Hur', 'Idleb', 'Iss', 'Jaberiyeh Amudeh', 'Jaberiyeh Jawadiyeh',
                'Jadeen', 'Jalabiyeh', 'Jalma - Jandairis', 'Jamel', 'Jamiliya (Darkosh)',
                'Jandairis', 'Janudiyeh', 'Jarablus', 'Jarez', 'Jarjnaz', 'Jasim',
                'Jawadiyah', 'Jazaa', 'Jazaret Elbuhmeid', 'Jazraya', 'Jbeileh',
                'Jdideh (Al-Hasakeh)', 'Jdideh (Suran)', 'Jdidet Bikara', 'Jdidet Faras',
                'Jeb Kas', 'Jisr-Ash-Shugur', 'Jisrein', 'Jizeh', 'Jobas', 'Joseph',
                'Jurneyyeh (Jurneyyeh)', 'Kafr - Kafrehmul', 'Kafr Aleppo',
                'Kafr Amma', 'Kafr Aruq', 'Kafr Batna', 'Kafr Deryan', 'Kafr Elward',
                'Kafr Hamra', 'Kafr Hum', 'Kafr Jales', 'Kafr Janna', 'Kafr Kalbein',
                'Kafr Musa', 'Kafr Nabi', 'Kafr Naha', 'Kafr Naseh Elatareb',
                'Kafr Nobol', 'Kafr Noran', 'Kafr Omeim (Saraqab)', 'Kafr Oweid',
                'Kafr Safra', 'Kafr Takharim', 'Kafr Zeita', 'Kafraya ( Maar Tamsarin)',
                'Kafrnaya', 'Kafrsajna', 'Kahil', 'Kaljibrin', 'Kalta', 'Karama (Karama)',
                'Karsaa', 'Kasra (Kisreh)', 'Kawkabeh (Kafr Nobol)', 'Kelly', 'Ketyan',
                'Khalfatli', 'Khan Eljabal', 'Khan Shaykun', 'Kharab Elasheq - Kharab Ishq',
                'Kharab Shahem', 'Khasham', 'Kherbet Elfaras (Tell Abiad)',
                'Kherbet Eljoz', 'Kherbet Elroz', 'Kishkiyeh', 'Kisret Elsheikh Jomaa',
                'Kisweh (Kisweh)', 'Kniseh - Mhambal', 'Kodneh', 'Korin', "Krum (A'zaz)",
                'Kusniya', 'Lattakia', 'Little Hayyeh', 'Little Orm', 'Lower Amiqa',
                'Lower Jrables', 'Lower Safira', "Ma'amoun", 'Maabada', 'Maadan',
                'Maar Dibsi', 'Maar Shamarin', 'Maar Shurin', 'Maar Tahroma',
                "Maarata (Ma'arrat An Nu'man)", 'Maaret Elekhwan', 'Maaret Elnaasan - Maaret Elhaski',
                "Maarin (A'zaz)", 'Maarrat An Numan', 'Maarrat Tamasrin', 'Maarzita',
                "Maasaran (Ma'arrat An Nu'man)", 'Mabtali', 'Madina', 'Madiq Castle',
                'Mafraq Siddiq', 'Mahdi', 'Mahmudli', 'Mansour', 'Mansura (Mansura)',
                'Marana (Kisweh)', 'Marata (Afrin)', 'Mare', 'Markada', 'Mastumeh',
                'Matmana', 'Mazaalah', 'Meidan Ekbis', 'Menbij', 'Mhambal', 'Mhemideh',
                'Milis', 'Moezleh (Deir-ez-Zor)', 'Moraba', 'Morshed Morshed Binar',
                'Mozra', 'Mqeilibeh', 'Mreimin Afrin', 'Mreiran', 'Mseifra',
                'Msheirfeh (Jisr-Ash-Shugur)', 'Muhasan', 'Murak', 'Murin',
                'Mutawaseta (Tal Tamer)', 'Mzeireb (Mzeireb)', 'Nabe Elfawar - Mzeireb',
                'Nabe Elsakher', 'Nahda', 'Nahj', 'Nahta', 'Namar', 'Nasib',
                'Nasriyeh (Nawa )', 'Nawa (Nawa )', 'Nayara', 'Nayrab', 'Northern Laj',
                'Northern Ora', 'Ojet Btir', 'Okath', 'Orm Eljoz', 'Qabasin',
                'Qadi Jrables', 'Qah', 'Qahtaniyyeh (Qahtaniyyeh)', 'Qalb Lozeh',
                'Qanater (Atareb)', 'Qanaya', 'Qarqas', 'Qastun', 'Qatmet Efrin',
                'Qaysiyeh', 'Qoqfin', 'Qosour', 'Qourqeena', 'Qseibeh (Al-Khashniyyeh)',
                'Quamishli', 'Qudsiya', 'Rael', 'Raeqqet Samra', 'Raffa', 'Rafid',
                'Rafqa', 'Raju', 'Ram Hamdan', 'Rami - Ehsem', 'Ras Al Ain (Ras Al Ain)',
                'Rashid', 'Rweheineh', 'Sabha', 'Sabka', 'Safya', 'Sahara', 'Sahwa',
                'Salaliyeh', 'Salama', 'Salhiyeh', 'Salqin', 'Sandi', 'Sanjar', 'Saqba',
                'Saraqab', 'Sarin', 'Sarmada', 'Sarmin', 'Sawa - Kisreh', "Sayda (Dar'a)",
                'Sayda (Fiq)', 'Sefsafa (Mansura)', 'Selwa', 'Sfuhen', 'Shaala',
                'Shabak', 'Shaddadah', 'Shafa ', 'Shamarin', 'Shaqra - Deir-ez-Zor',
                'Sharan (Ain al Arab)', 'Sharan (Sharan)', 'Sheikh El-Hadid', 'Shiheil',
                'Shmarekh', 'Shoruq - Holaqi', 'Shweiha ', 'Sijraz', 'Sokkariyeh (Tell Abiad)',
                'Sosa', 'Sosyan', 'Sukariyet Tal Elsamen', 'Sukkarieh (Suluk)',
                'Suluk', 'Sur - Sur', 'Suran (Aleppo)', 'Sweidan Jazira',
                'Tab Issa - Eastern And Western', 'Tabni', 'Tabriyat', 'Tafas',
                'Tal Akhdar - Tell Abiad', 'Tal Baydar Haskeh', 'Tal Brak', 'Tal Elamara',
                'Tal Elhajar - Tal Elahamar', 'Tal Elkaramej', 'Tal Elosud',
                'Tal Elsamen Dahham', 'Tal Habash', 'Tal Hajar', 'Tal Hammam',
                'Tal Hmis', 'Tal Majdal', 'Tal Othman', 'Tal Shihab', 'Tal Tamer',
                'Tal Tawil (Tal Tamer)', 'Tal Tufan', 'Talbiseh', 'Taldu', 'Talhiyeh',
                'Talil Elsham', 'Tall Refaat', 'Tanuriyeh', 'Tawi Rumman', 'Tayyana',
                'Teftnaz', 'Telamnas', 'Tell Abiad', 'Telqraq', 'Termanin',
                'Thahabiyeh (Saraqab)', 'Thahr Elmaghayer', 'Thiban (Thiban)',
                "Tiba (Dar'a)", 'Tilaada', 'Tishrine', 'Tishrine (Ar-Raqqa)',
                'Tlaline', 'Tromba', 'Turkman Bareh', 'Tweineh', 'Um Adase Near Manbaj',
                'Um Adaset Elfarat', 'Um Rabee', 'Upper Hweijeh', 'Upper Mawa - Upper Khanik',
                'Upper Tal Aswad', 'Upper Um Rotha', 'Wadi Elthaalab - Lower Jqal',
                'Waqf', 'Western Deir', 'Western Ghariyeh', 'Western Kharab Sehrij',
                'Western Maliha', 'Western Marj Akhdar', 'Western Raya', 'Western Sahlabiyeh',
                'Widyan', 'Yalda', 'Yarmuk (Damascus)', "Yarobiyah (Ya'robiyah)",
                'Zakyeh ', 'Zanbaqi', 'Zarbah', 'Zardana Mashehad', 'Zarzur', 'Zayadiyeh',
                'Zayzafun - Ekdeh', 'Zayzun (Mzeireb)', 'Ziyara', 'Zoghra', "al-Baali'ah "]

ALL_ADMIN_LOCATIONS = {'admin0_label' : ADMIN_0_LABELS,
                       'admin1_label' : ADMIN_1_LABELS,
                        'admin2_label' : ADMIN_2_LABELS, 
                        'admin3_label' : ADMIN_3_LABELS, 
                        'admin4_label' : ADMIN_4_LABELS, }